[Bot]
username = ""
password = ""
prefix = ""
nickname = ""
roomname = ""
chunk_limit = 0
debug = true
rainbow = true
restart_on_error = true
restart_attempts = 10
spellcheck_commands = true

[Modules]
enabled = [
    "Art",
    "Autourl",
    "Builtins",
    "Debug",
    "Chuck",
    "Conversion",
    "Covid",
    "DeathBattle",
    "Fun",
    "Movie",
    "Tokes",
    "Urban",
    "Wikipedia",
    "Wundertime",
    "Youtube"
]

[Modules.Art]

[Modules.Autourl]
# escape regex cause tomlkit
use_tor = false
tor_addr = "socks5://127.0.0.1:9050"
pattern = "http.*\\S"
exclusion_char = "!"
ignores = ["jumpin.chat", "tinychat.com\\/room\\/"]
whitelist_mode = false
whitelist = ["youtu(.be|.com)", "wikipedia.org"]

[Modules.Builtins]

[Modules.Chuck]

[Modules.Conversion]

[Modules.Covid]

[Modules.DeathBattle]

[Modules.Debug]
test = "Test Good"

[Modules.Fun]
8ballcustom = []
fancy_dice = true
allow_rate = true

[Modules.Jarvis]
wolframalpha_appid = ""

[Modules.Man]

[Modules.Movie]
api_key = ""

[Modules.Tokes]
hourly_420 = true
# these support the :emoji: things
cheers = ["â–‚â–…â–‡ ðŸ”¥ CHEERS ðŸ”¥ â–‡â–…â–‚"]
pre = [
    "packs their bowl",
    "is getting ready to toke",
    "wants to smoke some green",
    "is down to toke",
    "torches up"
]
post = [
    "lights up",
    "blazes",
    "bakes",
    "hotboxes your nan's bathroom",
    "puffs",
    "sparks their blunt",
    "lights their blunt",
    "sparks their joint",
    "lights their joint",
    "tokes",
    "sits this one out",
    "gets a shotgun from your mom",
    "rips their bong",
    "takes a fat dab",
    "dabs some reclaim"
]

[Modules.Urban]
blacklist = ["spam"]

[Modules.Webc]

[Modules.Wikipedia]
language = "en"
include_url = true
sentences = 2

[Modules.Wundertime]

[Modules.Youtube]
api_key = ""
